// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Data;

#nullable disable

namespace Store.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.Data.Models.ArticleDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id");

                    b.ToTable("Articles", t =>
                        {
                            t.HasCheckConstraint("CK_Articles_Price", "Price > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Труба",
                            Price = 50.5m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Корпус",
                            Price = 199m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Набор креплений",
                            Price = 23.78m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Утеплитель",
                            Price = 10.11m
                        });
                });

            modelBuilder.Entity("Store.Data.Models.OrderArticleDal", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ArticleQuantity")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderArticles", t =>
                        {
                            t.HasCheckConstraint("CK_Articles_Price", "ArticleQuantity > 0")
                                .HasName("CK_Articles_Price1");
                        });

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            OrderId = 1,
                            ArticleQuantity = 4
                        },
                        new
                        {
                            ArticleId = 2,
                            OrderId = 1,
                            ArticleQuantity = 1
                        },
                        new
                        {
                            ArticleId = 4,
                            OrderId = 1,
                            ArticleQuantity = 2
                        },
                        new
                        {
                            ArticleId = 3,
                            OrderId = 2,
                            ArticleQuantity = 3
                        });
                });

            modelBuilder.Entity("Store.Data.Models.OrderDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("Store.Data.Models.OrderArticleDal", b =>
                {
                    b.HasOne("Store.Data.Models.ArticleDal", "Article")
                        .WithMany("OrderArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Store.Data.Models.OrderDal", "Order")
                        .WithMany("OrderArticles")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Store.Data.Models.ArticleDal", b =>
                {
                    b.Navigation("OrderArticles");
                });

            modelBuilder.Entity("Store.Data.Models.OrderDal", b =>
                {
                    b.Navigation("OrderArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
